### ISSUE TITLE
Integrating the iOS SDK - App Freezes

### ISSUE THREAD

**Issue by marcos-lacerda** [BugBattle/iOS-SDK#2]
Hi, I'm having some issues integrating the iOS SDK with our app. During the app initialization the application freezes completely, it doesn't crash our show anything at the console, just gets frozen and nothing else works

**Comment by GEverding** [comment]
Hi, we're having the same issue. Can you please fix!

**Comment by boehlerlukas** [comment]
@GEverding Hey! Thank's for your message, I will take a closer look into that issue. Can you share some info's about the device you tested it on?

**Comment by GEverding** [comment]
Hi, iPhone running iOS 13.3.

--
Garrett
________________________________

**Comment by boehlerlukas** [comment]
Closed as of relaunch of V3 on monday.
