### ISSUE TITLE
Crash on iOS when starting the reporting flow

### ISSUE THREAD

**Issue by emeraldsanto** [BugBattle/iOS-SDK#3]
Hello!

I've experienced some crashes when users try to report a bug. I managed to reproduce the issue and get ahold of the specific error:

```
CALayer bounds contains NaN
```

I believe it may be caused by the `captureScreen` method:

```objc
/*
 Captures the current screen as UIImage.
 */
- (UIImage *) captureScreen {
    UIWindow *keyWindow = [[UIApplication sharedApplication] keyWindow];
    CGRect rect = [keyWindow bounds];
    UIGraphicsBeginImageContext(rect.size);
    CGContextRef context = UIGraphicsGetCurrentContext();
    [keyWindow.layer renderInContext:context];  // Possibly here?
    UIImage *img = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    return img;
}
```

**Comment by boehlerlukas** [comment]
Hey Yanick,

thanks for your feedback, i will take a look into it tomorrow!

Best,
Lukas

Yanick Bélanger <notifications@github.com> schrieb am Fr. 8. Mai 2020 um
19:22:

**Comment by boehlerlukas** [comment]
Hey @emeraldsanto !

Sorry for the late replay. I need to make some more tests. Could you tell me which iOS version / device you tested it on?

Best regards,
Lukas

**Comment by emeraldsanto** [comment]
@boehlerlukas I've tested on iPhones 6s and 11, both running iOS 13.3 I believe.

**Comment by boehlerlukas** [comment]
Closed as of relaunch of V3 on monday.
